[library]
[library.WOFOST]
language = "c"
library = "bmiwofostc"
header = "wofost_bmi.h"
entry_point = "register_bmi_wofost"

[build]
undef_macros = []
define_macros = []
libraries = []
library_dirs = []
include_dirs = []
extra_compile_args = []

[package]
name = "pymt_wofost"
requirements = [""]

[info]
github_username = "SnehaChevuru"
package_author = "Sneha Chevuru"
package_author_email = "s.chevuru@uu.nl"
package_license = "Not open source"
summary = "PyMT plugin for the C WOFOST model"

[ci]
python_version = ["3.9"]
os = ["linux", "mac", "windows"]

